AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Zendesk Translator

  Zendesk Translator lambda via partner eventbridge


Parameters:
  Environment:
    Type: String
  DebugParam:
    Type: String
  ZendeskKeySSMParameterPath:
    Type: String
  ZendeskUsernameMail:
    Type: String
  ZendeskSubdomain:
    Type: String
  ZendeskTicketLangFieldId:
    Type: String
  KmsKeyId:
    Type: String
  EventBusName:
    Type: String
    AllowedPattern: aws\.partner(/[\.\-_A-Za-z0-9]+){2,}
    MinLength: 1
    MaxLength: 256
    Description: Name of the Amazon EventBridge Zendesk Event Source to associate with an Event Bus. For example, aws.partner/zendesk.com/123456/default

#Manual step needs to be done before this can be run and that is to setup the eventbridge in the console of AWS Eventbridge (and follow instructions on zendesk side)
Resources:
  ZendeskEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Ref EventBusName
      EventSourceName: !Ref EventBusName

      
  EBZendeskTranslate:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub eb-zendesk-translate-${Environment}
      CodeUri: lambda/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Timeout: 10
      Environment:
        Variables:
          DEBUG: !Ref DebugParam
          ZENDESK_ACCESS_TOKEN_PARAM_KEY: !Ref ZendeskKeySSMParameterPath
          ZENDESK_SUBDOMAIN: !Ref ZendeskSubdomain
          ZENDESK_EMAIL: !Ref ZendeskUsernameMail
          ZENDESK_TICKET_LANG_FIELD_ID: !Ref ZendeskTicketLangFieldId
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Sid: AWStranslate
              Effect: Allow
              Action:
              - comprehend:DetectDominantLanguage
              - translate:TranslateText
              Resource: '*'
            - Sid: AWSssmParameterStore
              Effect: Allow
              Action:
              - ssm:GetParameter
              Resource:
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/config/zendesk-translation/*"
            - Sid: KmsDecryptZendesKey
              Effect: "Allow"
              Action:
              - kms:Decrypt
              Resource:
              - !Sub "arn:${AWS::Partition}:kms:${AWS::Region}:${AWS::AccountId}:key/${KmsKeyId}"

      Events:        
        InternalNote:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref EventBusName
            Pattern:
              account:
              - !Sub '${AWS::AccountId}'
              detail-type:
              - "Support Ticket: Comment Created"
              detail:
                ticket_event:
                  type:
                  - "Comment Created"
                  comment:
                    body:
                    - "prefix": "#translate"
                    is_public:
                    - false
                    author:
                      is_staff:
                      - true
                  ticket:
                    via:
                      channel:
                      - "email"
                      - "web"
        CustomerUpdate:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref EventBusName
            Pattern:
              account:
              - !Sub '${AWS::AccountId}'
              detail-type:
              - "Support Ticket: Comment Created"
              detail:
                ticket_event:
                  type:
                  - "Comment Created"
                  comment:
                    is_public:
                    - true
                    author:
                      is_staff:
                      - false
                  ticket:
                    via:
                      channel:
                      - "email"
                      - "web"

  ZendeskTranslatorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/eb-zendesk-translate-${Environment}
      RetentionInDays: 5


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  EBZendeskTranslate:
    Description: "Zendesk Translator lambda ARN"
    Value: !GetAtt EBZendeskTranslate.Arn
